### ISSUE TITLE
Support for split terminals

### ISSUE THREAD

**Issue by martinmeneval** [jlndr/vscode-terminal-setups#2]
Hey! This is looking really nice so far. It'd be amazing if there was an option to open terminal groups as split terminals:
```json
{
                "name": "Project Y",
                "split": true,
                "terminals" : [ ... ]
}

**Comment by jlndr** [comment]
Hi! Glad you enjoy it. That sounds like a good feature!

When you write the configuration like this:
```json
{
    "name": "Project Y",
    "split": true,
    "terminals": [...]
}
```
does that mean that all terminal should be split? If you use just 2 terminals in a setup its not an issue but say you use 4+, then it's not clear what should happen with all of them. Should they all be opened in a single split for example?

If we look at the [VSCode API](https://code.visualstudio.com/api/references/vscode-api#TerminalSplitLocationOptions) we can specify a `parentTerminal` as the terminal to split the new terminal beside. The option to split should maybe be moved to the individual terminal:

```json
{
    "name": "Project Y",
    "terminals": [
        {
            "name": "Term1",
            ...
        },
        {
            "name": "Term2",
            ...
            "parent": "Term1"
        }
    ]
}
```

This also means that you should be able to create multiple groups just be picking parents:

```json
{
    "name": "Project Y",
    "terminals": [
        {
            "name": "Term1",
        },
        {
            "name": "Term2",
            "parent": "Term1"
        },
        {
            "name": "Term3",
        },
        {
            "name": "Term4",
            "parent": "Term3"
        },
        {
            "name": "Term5",
            "parent": "Term3"
        },
    ]
}
```

Maybe `"parent"` is not the clearest naming, perhaps you could specify `"group": 1` to indicate that this terminal is part of the split group 1. Then just specify a group for the terminals you want in a split view:

```json
{
    "name": "Project Y",
    "terminals": [
        {
            "name": "Term1",
            "group": 1,
        },
        {
            "name": "Term2",
            "group": 1,
        },
        {
            "name": "Term3",
            "group": 2,
        },
        {
            "name": "Term4",
            "group": 2,
        },
        {
            "name": "Term5",
            "group": 2,
        },
    ]
}
```

What do you think @martinmeneval ?

**Comment by martinmeneval** [comment]
Hello!
Sorry, took a while to get back to this. Yes, the group naming seems to be what I had in mind.
It could also be done a slightly different way:
When you look at these split terminal from a user perspective, ignoring the API, the notion of parent terminal or groups is not really apparent:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/34133448/163194753-3ed1f14b-daab-412e-8c61-b964ee2dfb19.png">
Here we see 4 terminals that are joined together, and two that are not.
Your group number idea would look like this, IIUC:
```json
{
    "name": "Project Y",
    "terminals": [
        {
            "name": "split1",
            "group": 1,
        },
        {
            "name": "split2",
            "group": 1,
        },
        {
            "name": "split3",
            "group": 1,
        },
        {
            "name": "split4",
            "group": 1,
        },
        {
            "name": "nornal1",
            "group": 2,
        },
        {
            "name": "normal2",
            "group": 2,
        },
    ]
}
```
We could imagine nesting them instead, which is more compact:
```json

{
    "name": "Project Y",
    "terminals": [
        [
            {
                "name": "split1"
            },
            {
                "name": "split2"
            },
            {
                "name": "split3"
            },
            {
                "name": "split4"
            }
        ],
        {
            "name": "nornal1"
        },
        {
            "name": "normal2"
        }
    ]
}
```
This looks closer to what the user sees in the UI, but then the implementation logic could be a bit more complicated 🤔 
Let me know what you think!

**Comment by jlndr** [comment]
All good! @martinmeneval 

> ```json
> {
>     "name": "Project Y",
>     "terminals": [
>         [
>             {
>                 "name": "split1"
>             },
>             {
>                 "name": "split2"
>             },
>             {
>                 "name": "split3"
>             },
>             {
>                 "name": "split4"
>             }
>         ],
>         {
>             "name": "normal1"
>         },
>         {
>             "name": "normal2"
>         }
>     ]
> }
> ```
Fully agree, I feel like this is way better than the other alternatives. More compact and easier to use, nice! 👍  

Will look into implementing it soon.
